### ISSUE TITLE
rake db:setup abort: SQLite3::SQLException: no such table: alltime_standing_entries: DELETE FROM "alltime_standing_entries"

### ISSUE THREAD

**Issue by ashkang** [openbookie/sportbook#2]
I'm currently on master branch commit `f46e58f0dac2edc56b6261c4a64184539606ac6f`. rake db:setup complains with the following error: 

```
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: alltime_standing_entries: DELETE FROM "alltime_standing_entries"
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `initialize'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `new'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `prepare'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/sqlite_adapter.rb:246:in `block in exec_query'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/sqlite_adapter.rb:242:in `exec_query'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/sqlite_adapter.rb:268:in `exec_delete'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `delete'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/relation.rb:413:in `delete_all'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/querying.rb:7:in `delete_all'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sportdb-1.8.28/lib/sportdb/deleter.rb:14:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/sportdb-1.8.28/lib/sportdb.rb:198:in `delete!'
/root/tools/sportbook/db/seeds.rb:41:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.12/lib/rails/engine.rb:520:in `load_seed'
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/activerecord-3.2.12/lib/active_record/railties/databases.rake:333:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
```

**Comment by geraldb** [comment]
Thanks for trying sportbook. Please send setup issues to the [mailing list/forum](http://groups.google.com/group/opensport). Thanks.
